### PR TITLE
LPS-74443 Complete the doGetPlidFromPortletId() method which missing the operation for Full-Page-Application

### PR DESCRIPTION
**Pull request by Seiphon**
For this issue, the reason is that the doGetPlidFromPortletId() method is not completed, the operation for Full-Page-Application is missing. So I add the method to get the layout which has a full-page-application type. And I added the TYPE_FULL_PAGE_APPLICATION in the LayoutConstants class.

### CODE REVIEW

**Comment by yuhai** [comment]
Hi @Seiphon, 

Your commit info looks missed the LPS number. Could you please update it?

Thanks,
Hai

**Comment by Seiphon** [comment]
Hi @yuhai 

I have updated the commit info.

**Comment by yuhai** [comment]
thanks, just review.

**Comment by yuhai** [comment]
Hi @Seiphon,

The fix is not good enough for me. 

1. For PortalImpl.doGetPlidFromPortletId() method, it only handled with LayoutConstants.TYPE_PORTLET type layout. And it missed other layout type handle way. If we want to add them to this method, we need to add all type. For example, type:panel.

2. Compare with adding other type layouts, for example, we are getting fullPageApplication layouts by using the below method:
```
List<Layout> layouts_full_page = LayoutLocalServiceUtil.getLayouts(
 groupId, privateLayout, LayoutConstants.TYPE_FULL_PAGE_APPLICATION);
```
I think we may get all type's layouts in doGetPlidFromPortletId() as the below code:
```
List<Layout> layouts = LayoutLocalServiceUtil.getLayouts(
			groupId, privateLayout);

```
And then we may do some changes in https://github.com/yuhai/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/LayoutTypePortletImpl.java#L1521-L1538. Add other types judge. And then we may not add related logic regarding judge other types. Could you please try it?

Thanks,
Hai

**Pull request closed without merging**
