### PR TITLE
LPS-131959 run test

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
Hi @zhangyan0701, could you please help check the test result? Thanks.

**Comment by zhangyan0701** [comment]
Just started reviewing.

**Comment by zhangyan0701** [comment]
No related issues.

The SF failure is an known issue of master: see [this comment](https://issues.liferay.com/browse/LRQA-66355?focusedCommentId=2441299&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2441299).

Some integration tests failed with communication failure to MySQL, should be CI issue.

**Comment by yuhai** [comment]
thanks, @zhangyan0701

**Pull request closed without merging**
