### PR TITLE
LPS-79227 Unable to update site logo in Internet Explorer 11

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by yuhai** [comment]
Hi @ling-alan-huang,

I noticed the commit https://github.com/yuhai/liferay-portal/pull/60/commits/2aac41204d028baf22bf2c97ec7533a26cb7e4c8 is completely reverted for LPS-77632. If so, please alonely revert LPS-77632's every commit so that we can see the PR clearly.

That is to say, you may do three revert commit for LPS-77632. For revert action, you may use the command to do this. And then add your logic in the fourth commit.

Thanks,
Hai

**Comment by ling-alan-huang** [comment]
Hi @yuhai , I reverted each commit from LPS-79227 and than add my changes this time. Thanks.

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by yuhai** [comment]
just start reviewing :)

**Comment by yuhai** [comment]
send to Hugo for review.
https://github.com/hhuijser/liferay-portal/pull/3232

**Pull request closed without merging**
