### PR TITLE
LPS-83365 Workflow Issue in Knowledge Management

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:test

**Comment by daviddotzhang** [comment]
Hi @yuhai 
1: once a kb article is approved, we need to use "getResourcePrimKey" instead of  "getKbArticleId".

2: here is a same use case ->  "KBArticleImpl.java" -> "getClassPK()"

**Comment by yuhai** [comment]
just start reviewing

**Comment by yuhai** [comment]
Sent to Peter for review.
Please see the change from https://github.com/petershin/liferay-portal/pull/158

**Pull request closed without merging**
