### PR TITLE
[Remove Spring extender usages] LPS-161574 Break circular dependency between CommerceAddressLocalServiceImpl and CommerceOrderLocalServiceImpl

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr used moving logic from ALocalServiceImpl to BLocalServiceImpl to break circular dependency.

If we choose to use this way. I will send the pr to liferay-core-infra. I will run ci test in this pr.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
