### PR TITLE
[Technical Support] LPS-75041 Page permissions do not take effect in Navigation Menu portlet on the staging site after adding View Staging permission

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
Hi @dacousalr,

Thanks for your help. I can reproduce your mentioned regression issue. Sorry for this. I didn't find this.

It works for me. Could you please help push this PR to the next reviewer?

If you have further concerns, please let me know.

Regards,
Hai

**Comment by yuhai** [comment]
Hi @dacousalr ,

After talk with @samuelkong, I forward this to https://github.com/matethurzo/liferay-portal/pull/1805 to review.

Regards,
Hai

**Pull request closed without merging**
