### PR TITLE
LPS-78888 Improve Chinese and Japanese localized dates in the Header of Datepicker

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by yuhai** [comment]
Hi @ling-alan-huang, it seems there is a conflict file. could you please check it?

Thanks,
Hai

**Comment by ling-alan-huang** [comment]
ci: test

**Comment by ling-alan-huang** [comment]
Hi @yuhai , I resolved the conflict file. Thanks.

**Comment by yuhai** [comment]
sent to hugo for review.
Please check https://github.com/hhuijser/liferay-portal/pull/3223

**Pull request closed without merging**
