### PR TITLE
LPS-78888 Improve Chinese and Japanese localized dates in the Header of Datepicker

### PR DESCRIPTION
**Pull request by ling-alan-huang**
It's not customer related ticket.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by yuhai** [comment]
just start reviewing. :)

**Comment by yuhai** [comment]
Hi @ling-alan-huang, I think the fix logic is good. However, the language key "lang.b-y" name is not good. This should be a message. In my opinion, we may move the key https://github.com/yuhai/liferay-portal/blob/master/modules/apps/forms-and-workflow/calendar/calendar-web/src/main/resources/content/Language.properties#L29 to portal-impl.

**Comment by ling-alan-huang** [comment]
resend https://github.com/yuhai/liferay-portal/pull/58

**Pull request closed without merging**
