### PR TITLE
[DB2-issue] LPS-112222

### PR DESCRIPTION
**Pull request by yuhai**
@zhangyan0701, set currentSchema with upper case. Refer to https://stackoverflow.com/questions/24144538/why-do-i-get-sqlcode-204-sqlstate-42704-with-db2-luw-and-websphere-app-server. I think we may check db11.1 test result. DB 11.5 might be not upper case.

The attempt reason is schemas are upper case when I execute the command "db2 select schemaname from syscat.schemata" in db2.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:environments

**Comment by yuhai** [comment]
ci:test:environments

**Comment by yuhai** [comment]
ci:test:environments

**Comment by yuhai** [comment]
@zhangyan0701, refer to the latest test result. The issue can't be reproduced on 11.1. The fix didn't take effect in db2 11.5. Please refer to the content
`database.db2.url=jdbc:db2://test-1-30-69.lax.liferay.com_db2:25010/lportal:deferPrepares=false;fullyMaterializeInputStreams=true;fullyMaterializeLobData=true;progresssiveLocators=2;progressiveStreaming=2;`

The expected behavior is exist currentSchema=DB2INST1 in DB2 11.5. In the fix, I set it for ROOT for db2 11.1.

I will run the test again for db2 11.1. If the issue still can't be reproduced on db2 11.1, please apply the change for db2 11.5 and add integration test to run.

By the way, I am on pto today.

cc @vicnate5

**Comment by yuhai** [comment]
ci:test:environments

**Comment by yuhai** [comment]
@vicnate5, @zhangyan0701, I just see the [comment ](https://github.com/yuhai/liferay-portal/pull/292#issuecomment-1196045043). That is a good idea and let's firstly focus on 11.1. After the issue can't be reproduced on 11.1, we may try it on 11.5.
If the fix works in db2 11.1, please add integration test for 11.1 to run.

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by yuhai** [comment]
ci:test:environments

**Comment by yuhai** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
Hi @yuhai 

Error still occurs on 11.1 with property:
```
[beanshell] jdbc.default.jndi.name=
[beanshell] 
[beanshell] jdbc.default.driverClassName=com.ibm.db2.jcc.DB2Driver
[beanshell] jdbc.default.url=jdbc:db2://test-1-36-40.lax.liferay.com_db2:50000/lportal:currentSchema=ROOT;deferPrepares=false;fullyMaterializeInputStreams=true;fullyMaterializeLobData=true;progresssiveLocators=2;progressiveStreaming=2;
[beanshell] jdbc.default.username=root
[beanshell] jdbc.default.password=********
```

Full log:
https://testray.liferay.com/reports/production/logs/2022-07/test-1-35/test-portal-acceptance-pullrequest(master)/2133/functional-tomcat90-db2111-jdk8/1/14/jenkins-console.txt.gz?authuser=0

**Comment by yuhai** [comment]
@zhangyan0701, I checked the test result from https://github.com/yuhai/liferay-portal/pull/295#issuecomment-1195717847, the issue didn't happen in that test result. But the issue can be reproduced on https://github.com/yuhai/liferay-portal/pull/295#issuecomment-1195708287. It seems the issue didn't been reproduced every time.

**Comment by yuhai** [comment]
@zhangyan0701， the issue still can be reproduced in the latest test result

**Pull request closed without merging**
