### PR TITLE
LPS 107347 pr2

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-107347 SF, rename.
- LPS-107347 When setup wizard, the admin user's data won't be saved to MYSQL if the database changes from HSQL to MYSQL. It will use the default admin user data (passwordReset is false) when restarting the portal with MYSQL. The fix exports the property “default.admin.password.reset.enabled” when setup wizard. And then set it to default admin user when restarting the portal with the new MYSQL database. To keep the consistency with no database changed when setup wizard.
- LPS-107347 baseline
- LPS-107347 SF
- LPS-107347 SF, put more likely condition first

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai Please see my SF. I think "prefix@company_mx" should be the more common case for the admin user's email address, but you can correct it back if it's not.

And I just came up with one thing. Maybe it's not only the "reset password" option is lost when you set it in setup wizard and then restart portal to apply database configuration change.

For example, in `SetupWizardUtil`,

```
		String emailAddress = ParamUtil.getString(
			httpServletRequest, "adminEmailAddress",
			PropsValues.DEFAULT_ADMIN_EMAIL_ADDRESS_PREFIX + StringPool.AT +
				company.getMx());

		PropsValues.ADMIN_EMAIL_FROM_ADDRESS = emailAddress;

		unicodeProperties.put(PropsKeys.ADMIN_EMAIL_FROM_ADDRESS, emailAddress);

		String firstName = ParamUtil.getString(
			httpServletRequest, "adminFirstName",
			PropsValues.DEFAULT_ADMIN_FIRST_NAME);
		String lastName = ParamUtil.getString(
			httpServletRequest, "adminLastName",
			PropsValues.DEFAULT_ADMIN_LAST_NAME);
```

and also 

```
		User user = SetupWizardSampleDataUtil.updateAdminUser(
			company, themeDisplay.getLocale(), themeDisplay.getLanguageId(),
			emailAddress, firstName, lastName, passwordReset);
```

So the admin user's local/language id, email address, first name, last name can all be set on the setup wizard page -- and get lost after restarting portal to change the database, right? Could you please review the case? Maybe you should save them all to the properties file, and in `MainServlet`, call `SetupWizardSampleDataUtil.updateAdminUser` to update the admin user.

**Comment by dantewang** [comment]
@yuhai By the way, please send the next PR for this ticket to my repo without triggering the CI to let me take a look first. Thanks!

**Comment by dantewang** [comment]
@yuhai Also, if you want to save all of things that can get lost due to the restart to properties file, please make sure they have the same extra prefix under `SETUP_WIZARD`, maybe `SETUP_WIZARD_INITIALIZE_*` or other prefixes you feel better with.

**Comment by yuhai** [comment]
send it to https://github.com/dantewang/liferay-portal/pull/2134

**Pull request closed without merging**
