### PR TITLE
LPS-125550 test

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@tinatian @yuhai @dantewang After delete wstx.jar, there is no error when portal started. Here is the result:

Portal Version | Git Id | warmup(ms) | No.1 | No.2 | No.3 | No.4 | No.5 | Average Startup (ms) | Change
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 45a93292 | 47612 | 22,120 | 21,843 | 22,254 | 22,081 | 22,173 | 22,094.2 | -
PR-125550 | - | 73082 | 23602 | 23,802 | 23884 | 24,748 | 24111 | 24029.4 | 8.76%

**Pull request closed without merging**
