### PR TITLE
LPS-118542 01-07

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai 

I made some changes and squashed the commits. Please make further changes:

For Log4JOutputTest:

1. The dynamic parts in a text output are date, line number and exception stack trace (which also has line number), right? We should keep the matching logic to assert date format untouched, but change the logic to avoid using regex matching for the "content" part of the output in `_assertTextLog`. To do this, you can either
    - build expected strings from level to the position before the line number, then after the line number to end of line, and break the output content into 2 parts before & after the line number, and assert equals for these expected strings vs the actual output parts;
    - treat the output as a stream of characters and "components", so you extract the first several characters and assert it's date by matching the date format, then extract a space + characters + a space and assert it equals to space + expected level + space, etc. In this way, you can just skip the line number.
2. For exception part in `_assertTextOutput`, please add logic to assert there are stacktraces. No need to do exact match, but just do existence assertion.
3. After changing `_assertTextOutput` please also change `_assertXmlOutput` to follow the same way. Avoid any modification on the `actualOutput`.

For Log4JUtilTest, I havn't reviewed all of it yet. One question for now: why are there 2 xml files for it? Can it be merged into 1 file?

For ModuleLog4JTest (the integration test), if you want to assert it's at the configured level, you need to assert the current level enabled but a looser level not. This logic may also be used in Log4JUtilTest, so maybe you can extract a common util for it.

cc @tinatian

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
> why are there 2 xml files for it? Can it be merged into 1 file?
portal-log4j-ext.xml is testing for overriding portal-log4j.xml.  log4j.xml is testing for the current config files. It may merge to one file, I can only use portal-log4j-ext.xml.

**Comment by tinatian** [comment]
@dantewang @yuhai If there is still question about one of the tests, then send the other one first.

Thanks.
Tina.

**Pull request closed without merging**
