### PR TITLE
LPS-74443 Complete the doGetPlidFromPortletId() method

### PR DESCRIPTION
**Pull request by Seiphon**
For this issue, the reason is that the doGetPlidFromPortletId() method is not completed, the operation for Full-Page-Application and Panel are missing. So I add the method to get the layout which has a full-page-application type. And I added the TYPE_FULL_PAGE_APPLICATION in the LayoutConstants class.

### CODE REVIEW

**Comment by yuhai** [comment]
just starting review :)

**Comment by yuhai** [comment]
Hi @Seiphon 

The fix logic is good for you. However, the implement is not good for me.  Please refer to the below reasons.

1. For the code fragment https://github.com/Seiphon/liferay-portal/blob/cac3c26f0113238147b4f59db5b428a06320b9d6/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L7586-L7588, we have existed method (layoutTypePortlet.hasPortletId()) to do this. So we should use that logic.

2. For full_page_application type layout, it belongs to typePortlet (https://github.com/yuhai/liferay-portal/blob/master/modules/apps/web-experience/layout/layout-type-controller/layout-type-controller-full-page-application/src/main/java/com/liferay/layout/type/controller/full/page/application/internal/controller/FullPageApplicationLayoutTypeController.java#L54). We may add the logic https://github.com/Seiphon/liferay-portal/pull/1/commits/a20037be571160b42a346d7ac43fb4cf7d4bae70#diff-43e12bcae0c197d50b444e430484e1f9 to add related column.

After the above steps, we can extract the same logic to one method.

By the way, for the var name "layouts_full". it is not good. If you want to call this different name, you may name it as layoutsFull.

Please refer to https://github.com/Seiphon/liferay-portal/pull/1, if this is good for you. I will forward the PR to review.

Thanks,
Hai

**Comment by yuhai** [comment]
Hi @Seiphon 

Sent it to Hugo for review.
https://github.com/hhuijser/liferay-portal/pull/3237

Please comment your test result.

Thanks,
Hai

**Comment by Seiphon** [comment]
Hi @yuhai 
I have tested it. It works normally.
Seiphon

**Comment by yuhai** [comment]
thanks, @Seiphon

**Pull request closed without merging**
