### PR TITLE
LPS-77819 Wrong language setting of time format

### PR DESCRIPTION
**Pull request by ling-alan-huang**
It's not customer related ticket.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by yuhai** [comment]
just review :)

**Comment by yuhai** [comment]
Hi @ling-alan-huang,

Sent to hugo for review.
Please also check the changes from https://github.com/hhuijser/liferay-portal/pull/3224

Thanks,
Hai

**Pull request closed without merging**
