### PR TITLE
[Remove Spring extender usages] LPS-159581

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, this is just update. The pr is for **com.liferay.commerce.service**. It also included index part. I will follow your fix way if https://github.com/liferay-core-infra/liferay-portal/pull/1324 is passed. In the meantime, I will run ci:test in this pr.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:commerce

**Comment by yuhai** [comment]
@zhangyan0701, please help scan the test result.

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
