### PR TITLE
Lps 76937

### PR DESCRIPTION
**Pull request by Seiphon**
The reason of this issue is that the ContactsCenterRequestInterpreter is not to be set as a service. So I set is as a service, then the list called "_requestInterpreters" will exit the interpreter. Finally, I add a title in the Language.properties file.

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test

**Comment by yuhai** [comment]
just reviewing. :)

**Comment by yuhai** [comment]
Hi @Seiphon 

The fix is not good for me. Please refer to the below explanation:

1. You added PROFILE portlet in ContactsCenterRequestInterpreter class. This is not mapping. ContactsCenterRequestInterpreter used for ContactsCenterPortlet. Please refer to https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/contacts/contacts-web/src/main/java/com/liferay/contacts/web/internal/social/ContactsCenterActivityInterpreter.java#L37

Actually, the issue also occur when send one connect link in ContactsCenterPortlet. If your fix is for ContactsCenterPortlet in ContactsCenterRequestInterpreter class, this will be good for me. It seem we need to add this ProfileRequestInterpreter alone for PROFILE portlet.

2. If you want to add lang key, please separate for new commit. In addition, I have a concern regarding this. You want to modify the fix in com.liferay.contacts.web module, however, you added the language key in portal-impl. This is also wired. Every module have owns content folder which we manage the language key. Please also concern it.

I will close this PR and please resend it.

Thanks,
Hai

**Comment by yuhai** [comment]
Base on our talk, ProfilePortlet extends ContactsCenterPortlet. When request comes from ProfilePortlet, we may change portletId for ContactsCenterPortlet. instead of creating new ProfileRequestInterpreter class.

**Pull request closed without merging**
