### PR TITLE
LPS-149266

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @yuhai ,

Can you please help me to review my work, please?
Thanks for checking!
For your reference:
https://github.com/liferay-core-infra/liferay-portal/pull/792.
https://issues.liferay.com/browse/LPS-149266

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by yuhai** [comment]
Hi @jeffwu0724，

Sorry, I missed the pr due to I didn't get email notification when someone @ me from github (about 2 days). After I changed my github account setting, it worked for me. I got an email notification when you push force new changes. Do I need to check the pr? I noticed Dante worked on it.

Regards,
Hai

**Comment by jeffwu0724** [comment]
> Hi @jeffwu0724，
> 
> Sorry, I missed the pr due to I didn't get email notification when someone @ me from github (about 2 days). After I changed my github account setting, it worked for me. I got an email notification when you push force new changes. Do I need to check the pr? I noticed Dante worked on it.
> 
> Regards, Hai

Hey @yuhai ,

No worries, and I am glad that you get it fixed now! And yes, Dante has helped me review the codes, really appreciate your help and kindness!

Best,
Jeff

**Pull request closed without merging**
