### PR TITLE
LPS-122481 log output

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:environments

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by Wa1ter-Shao** [comment]
ci:help

**Comment by Wa1ter-Shao** [comment]
ci:test:upgrade-all

**Comment by yuhai** [comment]
ci:stop

**Pull request closed without merging**
