### PR TITLE
LPS-80957 Using unitSet to validator the attributes

### PR DESCRIPTION
**Pull request by Seiphon**
Reason:
For this issue, invalid css like "border-width:;border-style:" is displayed in source view, that because user didn't give any value for these styles. And the default value of them is "blank". When the ufaBorderWidth and ufaBorderStyle are false, the value shouldn't be null, the value should have "unit" follow.

Solution:
My solution is using unitset to check, if the value is null, then this attribute will not be added to final CSS.

### CODE REVIEW

**Comment by yuhai** [comment]
I will review this tomorrow morning.

**Comment by yuhai** [comment]
just reviewing :)

**Comment by yuhai** [comment]
Hi @Seiphon 

The fix is good for me. In order to check the fix  clearly, could you please divide the fix into two commits?

The first commit is when ufaBorderWidth is false.
The second commit is when ufaBorderWidth is true.

Thanks,
Hai

**Comment by Seiphon** [comment]
Hi @yuhai 
Ok, I will do it.

**Pull request closed without merging**
