### PR TITLE
Lps 83223 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevent

**Comment by yuhai** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:test:relevent

**Comment by yuhai** [comment]
just start reviewing :).

**Comment by yuhai** [comment]
Hi @arthurchan35,

I think the root issue is ChangesetPortlet property definition wrong. Please refer to https://github.com/liferay/liferay-portal/blob/master/definitions/liferay-portlet-app_7_1_0.dtd#L478-L485. For ChangesetPortlet, its preferences-unique-per-layout should false. One group should own one ChangesetPortlet, for example, https://github.com/liferay/liferay-portal/blob/master/modules/apps/wiki/wiki-web/src/main/java/com/liferay/wiki/web/internal/portlet/WikiAdminPortlet.java#L46.

Please check this.

Thanks,
Hai

**Pull request closed without merging**
