### PR TITLE
[Remove Spring extender usages]  LPS-161574 Break circular dependency between CommerceAddressLocalServiceImpl and CommerceOrderLocalServiceImpl

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang.

This is just update.

In CommerceAddressLocalServiceImpl, there are two methods to use CommerceOrderLocalService. For now, I remove CommerceOrderLocalService from one method. I will run ci test in this pr and ask Summer to check if the current change worked next Monday.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@zhangyan0701,ci test displayed the info **"This pull contains no unique failures."**. I can understand ci test passed? If not, please help scan the test result. Thanks.

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
> @zhangyan0701,ci test displayed the info **"This pull contains no unique failures."**. I can understand ci test passed? If not, please help scan the test result. Thanks.

Yes, the relevant test passed. I also triggered ci:test:commerce just to be save.

**Comment by yuhai** [comment]
ci:stop

**Comment by yuhai** [comment]
send it to https://github.com/liferay-core-infra/liferay-portal/pull/1490 to review

**Pull request closed without merging**
